version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NAMA_PRAKTIKAN=Muhammad Maulana Adrian
      - NIM_PRAKTIKAN=2408647
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
